config/routes.rb
Vtest::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "social_accounts"}
  devise_scope :user do
    get '/auth/:provider' => 'social_accounts#passthru'
    get '/auth/:provider/callback' => 'social_accounts#create'
  end

  root 'home#index'
  
  
  resources :user_accounts do
    member do
      post :follower
    end
    collection do
      put :change_password
    end
  end
  resources :videos

  

end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  before_filter :is_login?,:only => [:edit,:update,:show]
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You will receive an email with instructions about how to confirm your account in a few minutes."
      redirect_to root_path
    else
      render :action => :new
    end
  end
  
  def show
    @user = User.find params[:id]
    @followers = @user.followers.count
    @followings = @user.followings.count
    @fb = true if Authorization.exists?(:user_id => @user.id,:provider => 'facebook')
    @tw = true if Authorization.exists?(:user_id => @user.id,:provider => 'twitter')
    @tweet = Tweet.find_by_user_id_and_following_id(current_user.id,@user.id)
    if @tweet
      @follow = @tweet.follow
    else
      @follow = false
    end
  end
  
  def edit
    @user = current_user
    @fb = true if Authorization.exists?(:user_id => @user.id,:provider => 'facebook')
    @tw = true if Authorization.exists?(:user_id => @user.id,:provider => 'twitter')
  end
  
  def update
    @user = current_user
    @fb = true if Authorization.exists?(:user_id => @user.id,:provider => 'facebook')
    @tw = true if Authorization.exists?(:user_id => @user.id,:provider => 'twitter')
    if @user.update_attributes(user_params)
      redirect_to root_path
    else
      render :action => :edit
    end
  end
  
  def change_password
    current_user.errors.add(:password, 'is required') if params[:user].nil? or params[:user][:password].to_s.blank?
    if current_user.errors.empty? and current_user.update_with_password(user_params)
      sign_in(:user, current_user, :bypass => true)
      flash.now[:notice] = "Your Password Changed Successfully."
    end
    respond_to do |format|
      format.js
    end
  end
  
  def follower
    @user = User.find params[:id]
    @tweet = Tweet.find_by_user_id_and_following_id(current_user.id,@user.id)
    if @tweet
      @tweet.update_attribute(:follow,params[:follow])
      @follow = @tweet.follow
    else
      @tweet = Tweet.create(:user_id => current_user.id,:following_id => @user.id,:follow => params[:follow])
      @follow = @tweet.follow
    end
    @followers = @user.followers.count
    @followings = @user.followings.count
    respond_to do |format|
      format.js
    end
  end
  
  private
  def user_params
    params.require(:user).permit!
  end
  
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/views/user_accounts/_change_password.html.erb
<div class="popup">
  <div class="content .popupVisible">
    <%= form_for current_user,:url => change_password_user_accounts_path,:remote => true,:method => :put do |f| %>
      <% if current_user.errors.any? %>
        <ul>
          <% current_user.errors.each do |attr,msg| %>
            <li style="color:red;"><%= attr %>&nbsp;<%= msg %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="settContainer">
        <h2>Change Password</h2>
        <div class="passwordBox">
          <span>Old Password <div class="smalltxt">Forgot your password?</div>   </span>
          <div class="textbox">
            <%= f.password_field :current_password %>
          </div>
        </div>
        <div class="passwordBox">
          <span>New Password</span>
          <div class="textbox">
            <%= f.password_field :password %>
          </div>
        </div>
        <div class="passwordBox">
          <span>New Password, Again</span>
          <div class="textbox">
            <%= f.password_field :password_confirmation %>
          </div>
        </div>
        <div class="footerbox">
          <%= f.submit "Change Password",:id => "spw",:class => "button_n" %>
          <a href='/' class="button_n">Cancel</a>
        </div>

      </div>
    <% end %>
  </div>
  <%= link_to image_tag("closelabel.png",:class=>"close_image", :title=>"close"),"#",:id => "close_password_form",:class => "close" %>
</div>
<script>
  $("#close_password_form").click(function() {
    $("#facebox_overlay").hide();
    $("#facebox").hide();
    return false;
  });
</script>

app/views/user_accounts/change_password.js.erb
<% if current_user.errors.any? %>
  $("#facebox").html("<%= escape_javascript render :partial => "user_accounts/change_password" %>");
<% else %>
  window.location.href = '<%= edit_user_account_path(current_user) %>'
<% end %>

app/views/user_accounts/follower.js.erb
$("#follow_link").html('<%= @follow == false ? (link_to 'Follow',follower_user_account_path(:id => @user.id,:follow => true),:method => :post,:remote => true,:class=>"follow") :(link_to 'Unfollow',follower_user_account_path(:id => @user.id,:follow => false),:method => :post,:remote => true,:class=>"follow") %>');
$("#followers").html('<%= @followers %>')
$("#following").html('<%= @followings %>')

app/views/user_accounts/new.html.erb
<div class="ac-wrapper">
  <div class="settings-form">
    <div class="ac-stig">
      <%= form_for @user,:url => user_accounts_path(@user) do |f| %>
        <% if @user.errors.any? %>
          <ul style='position:relative;left:44px;width:400px;'>
            <% @user.errors.each do |attr,msg| %>
              <li style='color:red;list-style-type: disc;'><%= attr %>&nbsp;<%= msg %></li>
            <% end %>
          </ul>
        <% end %>
        <div class="fm-row">
          <div class="row">
            <div class="col4 first"><label class="lbl-fmx">Username</label></div><!-- end .col4 section -->	
            <div class="col8 last">
              <div class="row">
                <div class="col3 first svn-rgt vcr">
                  <label class="lbtm"></label>
                </div><!-- end col6 section -->
                <div class="row">
                  <%= f.text_field :username,:placeholder => "enter your full name..",:class => "input-ui fluid" %>
                </div><!-- end .col6 section -->	
              </div><!-- end .row section -->	
            </div><!-- end .col8 section -->	
          </div><!-- end .row section -->	
        </div><!-- end .fm-row section --> 
        <div class="fm-row">
          <div class="row">
            <div class="col4 first"><label class="lbl-fmx">Email Address</label></div><!-- end .col4 section -->	
            <div class="col8 last">
              <div class="row">
                <%= f.email_field :email,:placeholder => "enter your email address..",:class => "input-ui fluid" %>
              </div><!-- end .row section -->	
            </div><!-- end .col8 section -->	
          </div><!-- end .row section -->	
        </div><!-- end .fm-row section -->
        <div class="fm-row">
          <div class="row">
            <div class="col4 first"><label class="lbl-fmx">Password</label></div><!-- end .col4 section -->	
            <div class="col8 last">
              <div class="row">
                <%= f.password_field :password,:class => "input-ui fluid" %>
              </div><!-- end .row section -->	
            </div><!-- end .col8 section -->	
          </div><!-- end .row section -->	
        </div><!-- end .fm-row section -->
        <div class="fm-row">
          <div class="row">
            <div class="col4 first"><label class="lbl-fmx">Confirm Password</label></div><!-- end .col4 section -->	
            <div class="col8 last">
              <div class="row">
                <%= f.password_field :password_confirmation,:class => "input-ui fluid" %>
              </div><!-- end .row section -->	
            </div><!-- end .col8 section -->	
          </div><!-- end .row section -->	
        </div><!-- end .fm-row section -->
        <div class="fm-buttons clear">
          <a class="xbutn" href='/'>Cancel</a>
          <input class="xbutn red" type="submit" value="Create" />
        </div><!-- end section -->  
      </div><!-- end section -->
    <% end %>
  </div><!-- end .settings-forms section -->
</div><!-- end .ac-wrapper section -->
<div></div><!-- end section -->

app/views/user_accounts/show.html.erb
<div class="full-wrapper header-text3">
  <div class="grid-wrapper">
    <div class="inner-pad">
      <div class="topsy clear">
        <div class="topsy-l">
          <div class="prom">
            <div class="pro-imager"><%= @user.avatar.blank? ? image_tag("dani.png") : image_tag(@user.avatar,:width => "60",:height => "60") %></div><!-- end .pro-imager section -->
            <div class="pro-textr">
              <div class="psoc">
                <h3><%= @user.username %></h3>
                <% if @fb %><a href="#"><%= image_tag("facebook.png") %></a><% end %>
                <% if @tw %><a href="#"><%= image_tag("twitter.png") %></a><% end %>	
                <% if @li %><a href="#"><%= image_tag("icn1.png",:width=>"38",:height => "38") %></a><% end %>		
              </div>
              <div class="pxc">
                <div><span><strong><%= @user.username %> </strong> - pro surfer (web) + crative director + husband</span></div>
                <div><span><a href="#"><%= @user.website %></a></span></div>
              </div>
            </div><!-- end .pro-textr section -->
          </div><!-- end .prom section -->
        </div><!-- end .topsy-l section -->
        <div class="topsy-r">
          <ul>
            <li class="fr">
              <h3 id="followers"><%= @followers %></h3>
              <span>followers</span>
            </li>
            <li>
              <h3 id="following"><%= @followings %></h3>
              <span>following</span>
            </li>
            <li>
              <h3><%= @user.videos.count %></h3>
              <span>videos</span>
            </li>
            <% if current_user.id != @user.id %>
              <li>
                <h3 id="follow_link"><%= @follow == false ? (link_to 'Follow',follower_user_account_path(:id => @user.id,:follow => true),:method => :post,:remote => true,:class=>"follow") :(link_to 'Unfollow',follower_user_account_path(:id => @user.id,:follow => false),:method => :post,:remote => true,:class=>"follow") %></h3>
                <span></span>
              </li>
            <% end %>
          </ul>
        </div><!-- end .topsy-r section -->
      </div><!-- end .topsy section -->
      <div></div><!-- end section -->
    </div><!-- end .inner-pad section -->
  </div><!-- end .grid-wrapper section -->
</div><!-- end .full-wrapper .header-text section -->
<div class="full-wrapper">
  <div class="grid-wrapper">
    <div class="inner-pad">

      <div class="vidr-container">
        <div class="vid-flip">
          <ul class="tabs clear">
            <li><a href="#vid1" class="active">Vids 1</a></li>
            <li><a href="#vid2">Vids 2</a></li>
            <li><a href="#vid3">Vids 3</a></li>
          </ul>
          <div id="vid1" class="vidsect show">
            <div class="multi-vid clear">
              <% j = 3 %>
              <% i = 0 %>
              <% @user.videos.each do |video| %>
                <% i+=1 %>
                <div class="landing-vid <%= i == j ? "lastr" : nil %>">
                  <div class="landing-vid-inner">
                    <div class="pix-vid">
                      <a href="/videos/<%= video.id %>">
                        <%= image_tag(video.video(:large)) %>
                        <span class="vid-play"></span>
                      </a>
                      <div class="name-title"><h5><%= video.video_title %></h5></div><!-- end .name-title section -->
                    </div><!-- end .pix-vid section -->
                    <div class="vid-details">
                      <div class="vid-caps clear">
                        <div class="caps-pic"><%= video.user.avatar.blank? ? image_tag("profi.jpg",:width => "50px",:height => "50px") : image_tag(video.user.avatar(:thumb),:width => "50px",:height => "50px") %></div><!-- end .caps-pic section -->
                        <div class="caps-text">
                          <span class="creator">Created by:</span>
                          <span class="person"><%= video.user.username %></span>
                        </div><!-- end .caps-text section -->	
                      </div><!-- end .vid-caps section -->
                      <div class="vid-stats">
                        <ul>
                          <li><i class="icon-eye-open"></i><span>250</span></li>
                          <li><i class="icon-comment"></i><span>3</span></li>
                          <li><i class="icon-heart"></i><span>37</span></li>
                        </ul>
                      </div><!-- end .vid-stats section -->
                    </div><!-- end .vid-details section -->

                  </div><!-- end #landing-vid-inner section -->
                </div><!-- end #landing-vid section -->
                <% if i == j %><% j+=3 %><div style="clear: both; padding-top: 25px;"></div><% end %>
              <% end %>
            </div><!-- end multi-vid section -->

            <div class="steps-vid">

              <div class="vid-thumbs">
                <ul>
                  <% @user.videos.limit(4).each do |video| %>
                    <li><%= image_tag(video.video(:large)) %><span class="title"><%= video.video_title %></span></li>
                  <% end %>
                </ul>

                <div class="button-holder">
                  <%= image_tag("prev.png",:id => "prev",:alt=>"Previous video") %>
                  <%= image_tag("next.png",:id => "next",:alt=>"Next video") %>                            
                </div>

              </div>
            </div><!-- steps-vid -->

          </div>

        </div>

      </div><!-- end vidr-container -->              
    </div><!-- end .inner-pad -->    
  </div><!-- end section -->
</div><!-- end .full-wrapper .landing-content section -->

<div></div><!-- end section -->
<script type="text/javascript" src="/assets/video.js"></script> 
<script type="text/javascript" src="/assets/videojs-playlists.js"></script> 
<script type="text/javascript" src="/assets/init-video.js"></script>  