config/routes.rb
Vtest::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "social_accounts"}
  devise_scope :user do
    get '/auth/:provider' => 'social_accounts#passthru'
    get '/auth/:provider/callback' => 'social_accounts#create'
  end

  root 'home#index'
  
  
  resources :user_accounts do
    member do
      post :follower
    end
    collection do
      put :change_password
    end
  end
  resources :videos

  

end

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

app/views/layouts/_login.html.erb
<div class="full-wrapper">

  <div class="example gc3">

    <!-- form itself -->
    <%= form_for resource, :as => resource_name, :url => session_path(resource_name),:html =>{:id => "test-form",:class => "mfp-hide white-popup-block"},:remote => true do |f| %>
      <p>Login</p><p> Don't have an account yet? <%= link_to 'Sign up',new_user_account_path %></p>
      <div class="social-btns">
        <a href="/auth/twitter" class="tws"><i></i><span>Twitter</span></a>
        <a href="/auth/facebook" class="fbs"><i></i><span>Facebook</span></a>
      </div><!-- social buttons -->
      <div id="login-error-message"></div>
      <fieldset class="login-form" style="border:0;">
        <ol>
          <li>
            <label class="append-icon">
              <%= f.text_field :login,:id => "username",:class => "inputs",:autofocus => true,:placeholder => "usernae" %>
              <span><i class="icon-user"></i></span>
            </label>
          </li>
          <li>
            <label class="append-icon">
              <%= f.password_field :password,:class => "inputs",:id => "password",:placeholder => "password" %>
              <span><i class="icon-key"></i></span>
            </label>
          </li>
          <li class="lower">
            <label for="rmb" class="option">
              <input id="rmb" type="checkbox" checked>
              <span class="checkbox"></span>        
            </label>
            <label for="rmb" class="rpw">Remember Password</label> 

          </li>
          <%= f.submit "Sign in",:class => "buttonx pos"%>
        </ol>
      </fieldset>
    <% end %>
  </div>
</div>
<script>
  jQuery("#test-form").bind("ajax:complete", function(a, b) {
    jQuery("#login-error-message").html();
    if (b.status == "401") {
      jQuery("#login-error-message").css({"color": "red", "font-size": "12px"}).html(b.responseText);
    } else {
      window.location.href = '/';
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vtest</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= render :partial => "layouts/javascripts" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="background">
      <div class="bg-overlay"></div><!-- end .bg-overlay  section -->
      <div class="stretch-image one"></div><!-- end .stretch image section -->
    </div><!-- end #background section -->

    <div class="full-wrapper header">
      <div class="grid-wrapper">
        <div id="header">
          <div class="row">
            <div class="header-left left clear">
              <h3 id="logo"><a href="/">( Logo )</a></h3>
              <div id="searchbar">
                <div class="search-wrapper">
                  <form>
                    <input type="text" name="search" placeholder="Search..." title="Search..."  class="blink"  />
                    <button><i class="icon-search"></i></button>
                  </form>
                </div><!-- .search-wrapper -->
              </div><!-- end .search-bar section -->
            </div><!-- end .header-left section -->
            <div class="header-right right clear">
              <div class="profi userx">
                <div class="profi-pic"><%= current_user.avatar.blank? ? image_tag("profi.jpg") : image_tag(current_user.avatar(:thumb)) %></div><!-- end .profi-pic section -->
                <div class="profi-name"><span><%= link_to current_user.username,"/user_accounts/#{current_user.id}" %></span></div><!-- end section -->
                <ul style="width:136px;">
                  <li><%= link_to 'Logout',destroy_user_session_path,:method => :delete %></li>
                  <li><%= link_to "Account Settings",edit_user_account_path(current_user) %></li>
                  <li class="sep">Joined: <%= current_user.created_at.strftime("%b %d,%Y") %></li>
                </ul>	
              </div><!-- end .profi-name section -->
              <a href="/videos/new" class="vid-button"><i class="icon-facetime-video"></i> Upload new video </a>
            </div><!-- end .header-right section -->
          </div><!-- end .row section -->
        </div><!-- end #header section -->
      </div><!-- end .grid-wrapper section -->
    </div><!-- end .full-wrapper .header section -->
    <% ['notice', 'error', 'warning','alert'].each do |f|%>
      <% if flash[f.to_sym] %>
        <div class="<%= f %>"><%=  flash[f.to_sym] %></div>
      <% end %>
    <% end %>
    <%= yield %>
    <%= render :partial => "layouts/login" %>
    <% if params[:controller] != "user_accounts" and params[:action] != 'show' %>
      <div class="foot" style="background: white;">
        <div class="grid-wrapper">
          <div class="bottom-footer">
            <ul>
              <li> &copy; 2013 </li>
              <li><a href="#">About</a></li>
              <li><a href="#">Terms &amp; Conditions</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </div><!-- .bottom-footer -->        
        </div><!-- end .grid-wrapper section -->
      </div><!-- end .full-wrapper section -->
      <div></div><!-- end section -->
    <% end %>
    <script type="text/javascript" src="/assets/popup.min.js"></script>
    <script type="text/javascript" src="/assets/init-popup.js"></script> 
    <style>
      .bottom-footer ul li a{
        color:black;
      }
      .bottom-footer ul li{
        color:black;
      }
    </style>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vtest</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= render :partial => "layouts/javascripts" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="background">
      <div class="bg-overlay"></div><!-- end .bg-overlay  section -->
      <div class="stretch-image two"></div><!-- end .stretch image section -->
    </div><!-- end #background section -->

    <div class="full-wrapper header">
      <div class="grid-wrapper">
        <div id="header">
          <div class="row">
            <div class="header-left left clear">
              <h3 id="logo"><a href="/">( Logo )</a></h3>
              <% if current_user %>
                <div id="searchbar">
                  <div class="search-wrapper">
                    <form>
                      <input type="text" name="search" value="Search..." title="Search..."  class="blink"  />
                      <button><i class="icon-search"></i></button>
                    </form>
                  </div><!-- .search-wrapper -->
                </div><!-- end .search-bar section -->
              <% end %>
            </div><!-- end .header-left section -->
            <div class="header-right right clear">
              <% if current_user %>
                <div class="profi">
                  <div class="profi-pic"><%= current_user.avatar.blank? ? image_tag("profi.jpg") : image_tag(current_user.avatar(:thumb)) %></div><!-- end .profi-pic section -->
                  <div class="profi-name"><span><%= link_to current_user.username,edit_user_account_path(current_user) %></span></div><!-- end section -->	
                </div><!-- end .profi-name section -->
                <a href="/videos" class="vid-button"><i class="icon-facetime-video"></i> Upload new video </a>
                <%= link_to 'Log out',destroy_user_session_path,:method => :delete,:class => "vid-button login popup-with-form" %>
              <% else %>
                <a class="vid-button login popup-with-form" href="#test-form">Log in </a>
              <% end %>
            </div><!-- end .header-right section -->
          </div><!-- end .row section -->
        </div><!-- end #header section -->
      </div><!-- end .grid-wrapper section -->
    </div>
    <% ['notice', 'error', 'warning','alert'].each do |f|%>
      <% if flash[f.to_sym] %>
        <div class="<%= f %>"><%=  flash[f.to_sym] %></div>
      <% end %>
    <% end %>
    <%= yield %>
    <%= render :partial => "layouts/login" %>
    <div class="full-wrapper foot">
      <div class="grid-wrapper">
        <div class="bottom-footer">
          <ul>
            <li> &copy; 2013 </li>
            <li><a href="#">About</a></li>
            <li><a href="#">Terms &amp; Conditions</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div><!-- .bottom-footer -->        
      </div><!-- end .grid-wrapper section -->
    </div><!-- end .full-wrapper section -->
    <div></div><!-- end section -->
    <script type="text/javascript" src="/assets/popup.min.js"></script>
    <script type="text/javascript" src="/assets/init-popup.js"></script>  
  </body>
</html>